# 工作流名称
name: Sync-Images-From-DockerHub
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repos
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          #!/usr/bin/env bash
          # gitlab-ce
          # skopeo copy docker://docker.io/gitlab/gitlab-ce:17.2.9-ce.0 docker://registry.cn-shenzhen.aliyuncs.com/curry-public/gitlab-ce:17.2.9-ce.0
          # jenkins
          # skopeo copy docker://docker.io/jenkins/jenkins:2.462.3-lts docker://registry.cn-shenzhen.aliyuncs.com/curry-public/jenkins:2.462.3-lts
          # jenkins
          # skopeo copy docker://docker.io/jenkins/jenkins:2.319.1-lts docker://registry.cn-shenzhen.aliyuncs.com/curry-public/jenkins:2.319.1-lts
          # jenkins
          skopeo copy docker://docker.io/jenkins/jenkins:2.480 docker://registry.cn-shenzhen.aliyuncs.com/curry-public/jenkins:2.480

